### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by brianlebo** [netizen-ais/remote-sync-2#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.2.3
**Thrown From**: [remote-sync-2](https://github.com/netizen-ais/remote-sync-2) package 0.2.0

### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, read

```
At internal/fs/utils.js:220

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:506:3)
    at tryReadSync (fs.js:331:20)
    at Object.readFileSync (fs.js:368:19)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Proxy.md5ForPath (/packages/remote-sync-2/node_modules/fs-plus/lib/fs-plus.js:478:21)
    at RemoteSync.diff (/packages/remote-sync-2/lib/RemoteSync.js:385:12)
    at /packages/remote-sync-2/lib/RemoteSync.js:378:19
    at /packages/remote-sync-2/lib/commands/DownloadAllCommand.js:25:50
    at /packages/remote-sync-2/node_modules/async/dist/async.js:248:13
    at wrapper (/packages/remote-sync-2/node_modules/async/dist/async.js:268:20)
    at replenish (/packages/remote-sync-2/node_modules/async/dist/async.js:435:29)
    at iterateeCallback (/packages/remote-sync-2/node_modules/async/dist/async.js:424:21)
    at /packages/remote-sync-2/node_modules/async/dist/async.js:321:20
    at /packages/remote-sync-2/node_modules/async/dist/async.js:245:17
    at /packages/remote-sync-2/lib/transports/ScpTransport.js:136:56
    at /packages/remote-sync-2/node_modules/ssh2-streams/lib/sftp.js:1154:19
    at SFTPStream._transform (/packages/remote-sync-2/node_modules/ssh2-streams/lib/sftp.js:389:17)
    at SFTPStream.Transform._read (_stream_transform.js:189:10)
    at SFTPStream._read (/packages/remote-sync-2/node_modules/ssh2-streams/lib/sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:435:12)
    at writeOrBuffer (_stream_writable.js:419:5)
    at SFTPStream.Writable.write (_stream_writable.js:309:11)
    at Channel.ondata (_stream_readable.js:728:22)
    at Channel.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Channel.Readable.push (_stream_readable.js:224:10)
    at /packages/remote-sync-2/node_modules/ssh2/lib/Channel.js:167:15)
    at SSH2Stream.emit (events.js:223:5)
    at parsePacket (/packages/remote-sync-2/node_modules/ssh2-streams/lib/ssh.js:3191:10)
    at SSH2Stream._transform (/packages/remote-sync-2/node_modules/ssh2-streams/lib/ssh.js:701:13)
    at SSH2Stream.Transform._read (_stream_transform.js:189:10)
    at SSH2Stream._read (/packages/remote-sync-2/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:435:12)
```

### Commands

```
  3x -3:01.9.0 core:save (input.hidden-input)
  3x -2:35.1.0 core:backspace (input.hidden-input)
  2x -2:31.2.0 core:save (input.hidden-input)
     -1:53 remote-sync2:diff-folder (span.icon-file-directory.name.icon)
     -1:31.6.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
     -1:28.2.0 application:reopen-project (div#add-projects-view.)
     -1:15.5.0 remote-sync2:diff-folder (span.icon-file-directory.name.icon)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-debug-ui 1.0.4 
atom-ide-ui 0.13.0 
file-icons 2.1.47 
ide-php 0.7.18 
php-cs-fixer 4.2.0 
php-debug 0.3.5 
remote-sync-2 0.2.0 
remote-sync-pro 5.1.1 
```

**Comment by netizen-ais** [comment]
Please try to update the package and test again. Thank you

**Comment by brianlebo** [comment]
Thank you for the quick response...
