### ISSUE TITLE
Uncaught TypeError: Cannot read property 'downloadFile' of undefined

### ISSUE THREAD

**Issue by Dreamkk2** [netizen-ais/remote-sync-2#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [remote-sync-2](https://github.com/netizen-ais/remote-sync-2) package 0.2.4

### Stack Trace

Uncaught TypeError: Cannot read property 'downloadFile' of undefined

```
At C:\Users\Dreamkk2\.atom\packages\remote-sync-2\index.js:70

TypeError: Cannot read property 'downloadFile' of undefined
    at handleEvent (/packages/remote-sync-2/index.js:70:28)
    at /packages/remote-sync-2/index.js:147:47)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:352326)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:350801)
    at AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:1:833477)
    at EventEmitter.t (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:1:841531)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
     -0:59 core:confirm (input.hidden-input)
  2x -0:23.2.0 remote-sync2:download-file (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
remote-sync-2 0.2.4 
```

**Comment by netizen-ais** [comment]
Where are you launching that command?
